name: Builds
on: [push]
jobs:
  linux-opt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: make CC=cc OPT='-Os'
      - uses: actions/upload-artifact@v2
        with:
          name: minivm-linux
          path: minivm
      - uses: actions/upload-artifact@v2
        with:
          name: dis-linux
          path: dis
  macos-opt:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: make CC=cc OPT='-Os'
      - uses: actions/upload-artifact@v2
        with:
          name: minivm-mac
          path: minivm
      - uses: actions/upload-artifact@v2
        with:
          name: dis-mac
          path: dis
  windows-opt:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
      - run: make CC=cc OPT='-Os' minivm
      - uses: actions/upload-artifact@v2
        with:
          name: minivm-windows.exe
          path: minivm.exe
      - uses: actions/upload-artifact@v2
        with:
          name: dis-windows.exe
          path: dis.exe
